version: '3.3'

services:
  web:
    image: google_news
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    container_name: gnews
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    expose:
      - "8000"

  redis:
    image: redis:latest
    container_name: redis_gnews
    ports:
      - '6379:6379'
    volumes:
      - .:/redis_data

volumes:
  web:
  redis:
