name: Publish Docker Image to Docker Hub

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/gnewsapi

      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/gnewsapi
      
      - name: Create PEM file from secret
        run: echo "$EC2_SSH" > server.pem

      - name: connect to EC2
        run: |
          sudo chmod 400 server.pem && cat server.pem
          ssh -T -o StrictHostKeyChecking=no -i server.pem ubuntu@ec2-13-51-109-60.eu-north-1.compute.amazonaws.com
