name: Publish Docker Images and Deploy to EC2

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build and Push the "web" Docker image
      #   run: |
      #     docker build -t ${{ secrets.DOCKER_USERNAME }}/web -f Dockerfile .
      #     docker push ${{ secrets.DOCKER_USERNAME }}/web
      
      # - name: Build and Push the "redis" Docker image
      #   run: |
      #     docker build -t ${{ secrets.DOCKER_USERNAME }}/redis -f ./redis/Dockerfile .
      #     docker push ${{ secrets.DOCKER_USERNAME }}/redis

      - name: Build and Push the "nginx" Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx -f /nginx/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/nginx
      
      # - name: Create PEM file from secret
      #   run: |
      #     mkdir -p ~/.ssh/
      #     echo "${{ secrets.EC2_SSH }}" > ~/.ssh/server.pem
      #     chmod 400 ~/.ssh/server.pem

      # - name: Deploy to EC2
      #   run: |
      #     ssh -T -o StrictHostKeyChecking=no -i ~/.ssh/server.pem ${{ secrets.USER_NAME }}@${{ secrets.HOSTNAME }} << 'EOF'
      #       sudo apt-get update
      #       sudo docker system prune -af
      #       sudo docker pull ${{ secrets.DOCKER_USERNAME }}/web
      #       sudo docker pull ${{ secrets.DOCKER_USERNAME }}/redis
      #       sudo docker run ${{ secrets.DOCKER_USERNAME }}/web -d
      #       sudo docker run ${{ secrets.DOCKER_USERNAME }}/redis -d
      #     EOF
